### ISSUE TITLE
Add official Docker Compose example for OpenCloud behind external proxy manager

### ISSUE THREAD

**Issue by jabsammy** [opencloud-eu/opencloud-compose#3]
### Description
Currently the repository only offers Docker Compose examples with an integrated Traefik setup. We would like to have an official, well-documented Docker Compose configuration for running OpenCloud behind an existing reverse‑proxy manager (e.g. Nginx Proxy Manager, Caddy, etc.) that already handles SSL termination on ports 80/443.

## Is your feature request related to a problem? Please describe.
I assume that most people deploy new services behind an existing reverse‑proxy manager (e.g. Nginx Proxy Manager) and run into friction because the official examples only include an integrated Traefik setup. Managing two separate proxies (Traefik + NPM) adds unnecessary complexity and can lead to port conflicts, SSL‐termination confusion, and extra maintenance.

## Describe the solution you’d like
Provide an **official Docker Compose example** in this repository for running OpenCloud/OCIS behind an **external reverse proxy manager** (Nginx Proxy Manager, Caddy, etc.) that:

- **Excludes** Traefik entirely  
- **Exposes** only internal HTTP ports (9200 for web/API, 9980 for Collabora, optional 9300 for OnlyOffice/WOPI)  
- **Disables** internal TLS (`PROXY_TLS=false`, `COLLABORA_TLS=false`, `OPENCLOUD_INSECURE=false`)  
- Uses an environment variable `OPENCLOUD_URL=https://your.domain.tld` to tell OCIS its public URL  
- **Optionally mounts** `/etc/opencoud` (or `/etc/ocis`) so that `jwt_secret` and other configs can be auto‑generated on first run  
- Includes a new section in the README (“Behind external reverse proxy”) with step‑by‑step instructions on:
  - Which ports need to be exposed externally  
  - How to configure Proxy Hosts in NPM (domain, forward host, port, HTTP scheme, websockets support, SSL cert, Host header)  
  - Example Collabora/OnlyOffice integration  

## Describe alternatives you’ve considered
- **Maintaining a custom fork** of the official Traefik examples and stripping out Traefik myself  
- **Community examples** (Reddit, forums) showing manual `.env` and Compose tweaks, but these are unmaintained and scattered  
- **Running Traefik alongside NPM**, which doesn't work for me as my Forwarding rules send all port 80 and 443 requests directly to NPM.  

## Additional context
I’d like to run OpenCloud in an LXC on a Proxmox host with Nginx Proxy Manager (own LCX) already handling all other services. Community posts (e.g. [r/selfhosted](https://www.reddit.com/r/selfhosted/comments/1fpwi95/ocis_compose_file/)) highlight the pain of manually reworking the Traefik examples. An official, supported Compose setup would streamline deployments, reduce support requests, and align with the needs of many self‑hosters.

**Comment by BasesJs** [comment]
Literally came here to make this exact request. I spent a good chunk of time over the weekend trying to build my own docker compose and ran into some odd issues.

**Comment by rmortes** [comment]
I'm currently trying to deploy Opencloud behind coolify, which uses Trakefik/Caddy as a proxy. Can this be currently done?

**Comment by micbar** [comment]
I would do the following:

1. create a traefik.yml file
2. shift all labels for traefik and the traefik service to this file
3. use a condition in the .env file to make that optional

As soon as i would find time, I will create a pull request.

If the community would be  faster, I will be happy to review 😀

**Comment by samolego** [comment]
Is anyone willing to share their setup? I'm also trying to install it on existing nginx setup 🙃

**Comment by micbar** [comment]
Please check out https://github.com/opencloud-eu/opencloud-compose/

**Comment by micbar** [comment]
https://github.com/opencloud-eu/opencloud-compose/issues/1

**Comment by micbar** [comment]
> Example Collabora/OnlyOffice integration

OpenCloud will neither document nor create examples for the OnlyOffice integration because of low-trust.

Collabora it is.

**Comment by jabsammy** [comment]
Thanks for getting back! 
Unfortunately, I can't find anything except for a license file at your shared link.

Edit: just now realized that there is a starting-point branch. Gonna check it out and give feedback soon :)

**Comment by op4lat** [comment]
I'm using npm. I have set my proxy hosts with websocket support, ssl certificate, force ssl,  http scheme, and the domain names pointing all to the same host, with the ports below:

- opencloud.yourdomain.ltd 9200
- companion.yourdomain.ltd 9300 # probably not neede but it's there
- collabora.yourdomain.ltd 9980
- wopi.yourdomain.ltd http 9300

Here are my working (they seem to work *shrug*) yml files:

## .env
```
LOG_DRIVER=
INSECURE=true
TRAEFIK_DASHBOARD=
TRAEFIK_DOMAIN=
TRAEFIK_BASIC_AUTH_USERS=
TRAEFIK_ACME_MAIL=your@email.com
TRAEFIK_ACME_CASERVER=
OPENCLOUD=:opencloud.yml
OC_DOCKER_TAG=
OC_DOMAIN=opencloud.yourdomain.ltd
ADMIN_PASSWORD=
DEMO_USERS=
LOG_LEVEL=
LOG_PRETTY=true
OC_CONFIG_DIR=./ocdata/config
OC_DATA_DIR=./ocdata/data
DECOMPOSEDS3_ENDPOINT=
DECOMPOSEDS3_REGION=
DECOMPOSEDS3_ACCESS_KEY=
DECOMPOSEDS3_SECRET_KEY=
DECOMPOSEDS3_BUCKET=
MINIO_DOMAIN=
SMTP_HOST=
SMTP_PORT=
SMTP_SENDER=
SMTP_USERNAME=
SMTP_PASSWORD=
SMTP_AUTHENTICATION=
SMTP_TRANSPORT_ENCRYPTION=
SMTP_INSECURE=
START_ADDITIONAL_SERVICES="notifications"
EXTENSIONS=:web_extensions/extensions.yml
UNZIP=:web_extensions/unzip.yml
DRAWIO=:web_extensions/drawio.yml
JSONVIEWER=:web_extensions/jsonviewer.yml
PROGRESSBARS=:web_extensions/progressbars.yml
EXTERNALSITES=:web_extensions/externalsites.yml
COMPANION_IMAGE=
COMPANION_DOMAIN=companion.yourdomain.ltd
COMPANION_ONEDRIVE_KEY=
COMPANION_ONEDRIVE_SECRET=
TIKA_IMAGE=
COLLABORA=:collabora.yml
COLLABORA_DOMAIN=collabora.yourdomain.ltd
WOPISERVER_DOMAIN=wopi.yourdomain.ltd
COLLABORA_ADMIN_USER=
COLLABORA_ADMIN_PASSWORD=
COLLABORA_SSL_ENABLE=false
COLLABORA_SSL_VERIFICATION=false
CLAMAV_DOCKER_TAG=
INBUCKET_DOMAIN=
COMPOSE_PATH_SEPARATOR=:
LDAP_ADMIN_PASSWORD=
LDAP_MANAGER_DOMAIN=
IDP_DEFAULT_SIGNIN_PAGE_TEXT=
KEYCLOAK_DOMAIN=
KEYCLOAK_REALM=
KEYCLOAK_ADMIN_USER=
KEYCLOAK_ADMIN_PASSWORD=
COMPOSE_FILE=docker-compose.yml${OPENCLOUD:-}${TIKA:-}${DECOMPOSEDS3:-}${DECOMPOSEDS3_MINIO:-}${DECOMPOSED:-}${COLLABORA:-}${MONITORING:-}${IMPORTER:-}${CLAMAV:-}${INBUCKET:-}${EXTENSIONS:-}${UNZIP:-}${DRAWIO:-}${JSONVIEWER:-}${PROGRESSBARS:-}${EXTERNALSITES:-}${KEYCLOAK:-}${LDAP:-}${KEYCLOAK_AUTOPROVISIONING:-}${LDAP_MANAGER:-}${RADICALE:-}

```

## docker-compose.yml
```
# docker-compose.yml
---

volumes:
  certs:

networks:
  opencloud-net:
```

## collabora.yml
```
---
services:
  opencloud:
    environment:
      # make collabora the secure view app
      FRONTEND_APP_HANDLER_SECURE_VIEW_APP_ADDR: eu.opencloud.api.collaboration.CollaboraOnline
      GRAPH_AVAILABLE_ROLES: "b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5,a8d5fe5e-96e3-418d-825b-534dbdf22b99,fb6c3e19-e378-47e5-b277-9732f9de6e21,58c63c02-1d89-4572-916a-870abc5a1b7d,2d00ce52-1fc2-4dbc-8b95-a73b73395f5a,1c996275-f1c9-4e71-abdf-a42f6495e960,312c0871-5ef7-4b3a-85b6-0e4074c64049,aa97fe03-7980-45ac-9e50-b325749fd7e6"

  collaboration:
    image: ${OC_DOCKER_IMAGE:-opencloudeu/opencloud-rolling}:${OC_DOCKER_TAG:-latest}
    networks:
      opencloud-net:
    depends_on:
      opencloud:
        condition: service_started
      collabora:
        condition: service_healthy
    entrypoint:
      - /bin/sh
    command: [ "-c", "opencloud collaboration server" ]
    environment:
      COLLABORATION_GRPC_ADDR: 0.0.0.0:9301
      COLLABORATION_HTTP_ADDR: 0.0.0.0:9300
      MICRO_REGISTRY: "nats-js-kv"
      MICRO_REGISTRY_ADDRESS: "opencloud:9233"
      COLLABORATION_WOPI_SRC: https://${WOPISERVER_DOMAIN:-wopiserver.opencloud.test}
      COLLABORATION_APP_NAME: "CollaboraOnline"
      COLLABORATION_APP_PRODUCT: "Collabora"
      COLLABORATION_APP_ADDR: https://${COLLABORA_DOMAIN:-collabora.opencloud.test}
      COLLABORATION_APP_ICON: https://${COLLABORA_DOMAIN:-collabora.opencloud.test}/favicon.ico
      COLLABORATION_APP_INSECURE: "${INSECURE:-true}"
      COLLABORATION_CS3API_DATAGATEWAY_INSECURE: "${INSECURE:-true}"
      COLLABORATION_LOG_LEVEL: ${LOG_LEVEL:-info}
      OC_URL: https://${OC_DOMAIN:-cloud.opencloud.test}
    volumes:
      # configure the .env file to use own paths instead of docker internal volumes
      - ${OC_CONFIG_DIR:-opencloud-config}:/etc/opencloud
    ports:
      - 9300:9300
      - 9301:9301
    logging:
      driver: ${LOG_DRIVER:-local}
    restart: always

  collabora:
    image: collabora/code:25.04.1.1.1
    # release notes: https://www.collaboraonline.com/release-notes/
    networks:
      opencloud-net:
    environment:
      aliasgroup1: https://${WOPISERVER_DOMAIN:-wopiserver.opencloud.test}:443
      DONT_GEN_SSL_CERT: "YES"
      extra_params: |
        --o:ssl.enable=${COLLABORA_SSL_ENABLE:-true} \
        --o:ssl.ssl_verification=${COLLABORA_SSL_VERIFICATION:-true} \
        --o:ssl.termination=true \
        --o:welcome.enable=false \
        --o:net.frame_ancestors=${OC_DOMAIN:-cloud.opencloud.test}
      username: ${COLLABORA_ADMIN_USER:-admin}
      password: ${COLLABORA_ADMIN_PASSWORD:-admin}
    cap_add:
      - MKNOD
    ports:
      - 0.0.0.0:9980:9980
    logging:
      driver: ${LOG_DRIVER:-local}
    restart: always
    entrypoint: ['/bin/bash', '-c']
    command: ['coolconfig generate-proof-key && /start-collabora-online.sh']
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/127.0.0.1/9980 && echo -e 'GET /hosting/discovery HTTP/1.1\r\nHost: localhost:9980\r\n\r\n' >&3 && head -n 1 <&3 | grep '200 OK'"]

```

## opencloud.yml

```
---
services:
  opencloud:
    image: ${OC_DOCKER_IMAGE:-opencloudeu/opencloud-rolling}:${OC_DOCKER_TAG:-latest}
    # changelog: https://github.com/opencloud-eu/opencloud/tree/main/changelog
    # release notes: https://docs.opencloud.eu/opencloud_release_notes.html
    networks:
      opencloud-net:
    entrypoint:
      - /bin/sh
    # run opencloud init to initialize a configuration file with random secrets
    # it will fail on subsequent runs, because the config file already exists
    # therefore we ignore the error and then start the opencloud server
    command: ["-c", "opencloud init || true; opencloud server"]
    environment:
      # enable services that are not started automatically
      OC_ADD_RUN_SERVICES: ${START_ADDITIONAL_SERVICES}
      OC_URL: https://${OC_DOMAIN:-cloud.opencloud.test}
      OC_LOG_LEVEL: ${LOG_LEVEL:-info}
      OC_LOG_COLOR: "${LOG_PRETTY:-false}"
      OC_LOG_PRETTY: "${LOG_PRETTY:-false}"
      # do not use SSL between Traefik and OpenCloud
      PROXY_TLS: "false"
      # make the REVA gateway accessible to the app drivers
      GATEWAY_GRPC_ADDR: 0.0.0.0:9142
      # INSECURE: needed if OpenCloud / Traefik is using self generated certificates
      OC_INSECURE: "${INSECURE:-false}"
      # basic auth (not recommended, but needed for eg. WebDav clients that do not support OpenID Connect)
      PROXY_ENABLE_BASIC_AUTH: "${PROXY_ENABLE_BASIC_AUTH:-false}"
      # admin user password
      IDM_ADMIN_PASSWORD: "${ADMIN_PASSWORD:-admin}" # this overrides the admin password from the configuration file
      # demo users
      IDM_CREATE_DEMO_USERS: "${DEMO_USERS:-false}"
      # idp login form settings
      IDP_DEFAULT_SIGNIN_PAGE_TEXT: "${IDP_DEFAULT_SIGNIN_PAGE_TEXT}"
      # email server (if configured)
      NOTIFICATIONS_SMTP_HOST: "${SMTP_HOST}"
      NOTIFICATIONS_SMTP_PORT: "${SMTP_PORT}"
      NOTIFICATIONS_SMTP_SENDER: "${SMTP_SENDER:-OpenCloud notifications <notifications@${OC_DOMAIN:-cloud.opencloud.test}>}"
      NOTIFICATIONS_SMTP_USERNAME: "${SMTP_USERNAME}"
      NOTIFICATIONS_SMTP_PASSWORD: "${SMTP_PASSWORD}"
      NOTIFICATIONS_SMTP_INSECURE: "${SMTP_INSECURE}"
      NOTIFICATIONS_SMTP_AUTHENTICATION: "${SMTP_AUTHENTICATION}"
      NOTIFICATIONS_SMTP_ENCRYPTION: "${SMTP_TRANSPORT_ENCRYPTION:-none}"
      FRONTEND_ARCHIVER_MAX_SIZE: "10000000000"
      # make the registry available to the app provider containers
      MICRO_REGISTRY_ADDRESS: 127.0.0.1:9233
      NATS_NATS_HOST: 0.0.0.0
      NATS_NATS_PORT: 9233
      PROXY_CSP_CONFIG_FILE_LOCATION: /etc/opencloud/csp.yaml
      # these three vars are needed to the csp config file to include the web office apps and the importer
      COLLABORA_DOMAIN: ${COLLABORA_DOMAIN:-collabora.opencloud.test}
      # ONLYOFFICE_DOMAIN: ${ONLYOFFICE_DOMAIN:-onlyoffice.opencloud.test}
      COMPANION_DOMAIN: ${COMPANION_DOMAIN:-companion.opencloud.test}
      # enable to allow using the banned passwords list
      OC_PASSWORD_POLICY_BANNED_PASSWORDS_LIST: banned-password-list.txt
    volumes:
      - ./config/opencloud/app-registry.yaml:/etc/opencloud/app-registry.yaml
      - ./config/opencloud/csp.yaml:/etc/opencloud/csp.yaml
      - ./config/opencloud/banned-password-list.txt:/etc/opencloud/banned-password-list.txt
      # configure the .env file to use own paths instead of docker internal volumes
      - ${OC_CONFIG_DIR:-opencloud-config}:/etc/opencloud
      - ${OC_DATA_DIR:-opencloud-data}:/var/lib/opencloud
    ports:
      - 0.0.0.0:9200:9200
    logging:
      driver: ${LOG_DRIVER:-local}
    restart: always

volumes:
  opencloud-config:
  opencloud-data:
```

## create-datadirs.bash
```
#/usr/bin/env bash
# This script is used to reset opencloud

sudo -rf ./ocdata

mkdir -p ocdata/{config,data}
chown -R 1000:1000 ocdata
```

These file probably need more clean up, but I can login, create/edit spreadsheets, etc.

**Comment by ffuhrnew** [comment]
Thank you all very much. Thank You Michael for your repo here. I am so very happy now

It worked finally with caddy.
Caddyfile:

```
(cloudflare) {
        tls {
                dns cloudflare APIKEYFROMCLOUDFLARE
                resolvers 1.1.1.1
        }
}
(internalssl) {
        tls internal
}

{
        servers {
                protocols h1
        }
}

(logger) {
        {
                log {
                        output file /home/admin/ocaddy.log
                        format console
                        include http.log.access
                }
        }
}

*.fqdn.de {
        import cloudflare

        @cloud host cloud.fqdn.de
        @collabora host collabora.fqdn.de
        @wopiserver host wopiserver.fqdn.de
        handle @cloud {
                reverse_proxy opencloud:9200
                #               reverse_proxy http://172.19.0.3:9200
                #               reverse_proxy http://192.168.178.214:9200 
        }

        handle @collabora {
                reverse_proxy collabora:9980
                #               reverse_proxy http://172.19.0.2:9980
                #               reverse_proxy http://192.168.178.214:9980 
        }
        handle @wopiserver {
                reverse_proxy collaboration:9300
                #               reverse_proxy http://172.19.0.5:9300
                #               reverse_proxy http://192.168.178.214:9300
        }
}
```

Here the docker-compose.yml for caddy

```
services:
  caddy:
#    image: ffuhrnew/caddylabel:2.9.1

    image: ghcr.io/caddybuilds/caddy-cloudflare:latest

    cap_add:
      - NET_ADMIN


    container_name: caddy
    hostname: caddy
    environment:
      - CADDY_INGRESS_NETWORKS=opencloud-net

    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /home/admin/Caddyfile:/etc/caddy/Caddyfile
      - /mnt/docker/caddy/site:/srv
      - /mnt/docker/caddy/data:/data
      - /mnt/docker/caddy/config:/config
#      - /run/user/1000/docker.sock:/var/run/docker.sock
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      opencloud-net: null


networks:
  opencloud-net:
    name: opencloud-compose_opencloud-net

volumes:
  data:
  config:
  site:
```
And here is the full opencloud-stack with collabora:

```
name: opencloud-compose
services:
  collabora:
    container_name: collabora
    cap_add:
      - MKNOD
    command:
      - coolconfig generate-proof-key && /start-collabora-online.sh
    entrypoint:
      - /bin/bash
      - -c
    environment:
      DONT_GEN_SSL_CERT: "YES"
      aliasgroup1: https://wopiserver.fqdn.de:443
      extra_params: |
        --o:ssl.enable=false \
        --o:ssl.ssl_verification=true \
        --o:ssl.termination=true \
        --o:welcome.enable=false \
        --o:net.frame_ancestors=cloud.fqdn.de
      password: PASSWORD
      username: admin
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - "exec 3<>/dev/tcp/127.0.0.1/9980 && echo -e 'GET /hosting/discovery HTTP/1.1\r\nHost: localhost:9980\r\n\r\n' >&3 && head -n 1 <&3 | grep '200 OK'"
    image: collabora/code:24.04.13.2.1
    logging:
      driver: local
    networks:
      opencloud-net: null
    ports:
      - mode: ingress
        target: 9980
        published: "9980"
        protocol: tcp
    restart: always
  collaboration:
    container_name: collaboration
    command:
      - -c
      - opencloud collaboration server
    depends_on:
      collabora:
        condition: service_healthy
        required: true
      opencloud:
        condition: service_started
        required: true
    entrypoint:
      - /bin/sh
    environment:
      COLLABORATION_APP_ADDR: https://collabora.fqdn.de
      COLLABORATION_APP_ICON: https://collabora.fqdn.de/favicon.ico
      COLLABORATION_APP_INSECURE: "true"
      COLLABORATION_APP_NAME: CollaboraOnline
      COLLABORATION_APP_PRODUCT: Collabora
      COLLABORATION_CS3API_DATAGATEWAY_INSECURE: "true"
      COLLABORATION_GRPC_ADDR: 0.0.0.0:9301
      COLLABORATION_HTTP_ADDR: 0.0.0.0:9300
      COLLABORATION_LOG_LEVEL: info
      COLLABORATION_WOPI_SRC: https://wopiserver.fqdn.de
      MICRO_REGISTRY: nats-js-kv
      MICRO_REGISTRY_ADDRESS: opencloud:9233
      OC_URL: https://cloud.6qd.de
    image: opencloudeu/opencloud:latest
    logging:
      driver: local
    networks:
      opencloud-net: null
    ports:
      - mode: ingress
        target: 9300
        published: "9300"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /mnt/docker/opencloud/config
        target: /etc/opencloud
        bind:
          create_host_path: true

true
      - /mnt/docker/opencloud/data:/var/lib/opencloud

  opencloud:
    container_name: opencloud

    command:
      - -c
      - opencloud init || true; opencloud server
    entrypoint:
      - /bin/sh
    environment:
      COLLABORA_DOMAIN: collabora.fqdn.de
      FRONTEND_APP_HANDLER_SECURE_VIEW_APP_ADDR: eu.opencloud.api.collaboration.CollaboraOnline
      FRONTEND_ARCHIVER_MAX_SIZE: "10000000000"
      GATEWAY_GRPC_ADDR: 0.0.0.0:9142
      GRAPH_AVAILABLE_ROLES: b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5,a8d5fe5e-96e3-418d-825b-534dbdf22b99,fb6c3e19-e378-47e5-b277-9732f9de6e21,58c63c02-1d89-4572-916a-870abc5a1b7d,2d00ce52-1fc2-4dbc-8b95-a73b73395f5a,1c996275-f1c9-4e71-abdf-a42f6495e960,312c0871-5ef7-4b3a-85b6-0e4074c64049,aa97fe03-7980-45ac-9e50-b325749fd7e6
      IDM_ADMIN_PASSWORD: PASSWORD
      IDM_CREATE_DEMO_USERS: "false"
      NATS_NATS_HOST: 0.0.0.0
      NOTIFICATIONS_SMTP_AUTHENTICATION: ""
      NOTIFICATIONS_SMTP_ENCRYPTION: starttls
      NOTIFICATIONS_SMTP_HOST: smtp.gmail.com
      NOTIFICATIONS_SMTP_INSECURE: "false"
      NOTIFICATIONS_SMTP_PASSWORD: new pass
      NOTIFICATIONS_SMTP_PORT: "587"
      NOTIFICATIONS_SMTP_SENDER: opencloud notifications <noreply@yourdomain.com>
      NOTIFICATIONS_SMTP_USERNAME: mailname@googlemail.com
      OC_ADD_RUN_SERVICES: notifications
      OC_INSECURE: "false"
      OC_LOG_COLOR: "true"
      OC_LOG_LEVEL: info
      OC_LOG_PRETTY: "true"
      OC_PASSWORD_POLICY_BANNED_PASSWORDS_LIST: banned-password-list.txt
      OC_URL: https://cloud.fqdn.de
      PROXY_CSP_CONFIG_FILE_LOCATION: /etc/opencloud/csp.yaml
      PROXY_ENABLE_BASIC_AUTH: "false"
      PROXY_HTTP_ADDR: 0.0.0.0:9200
      PROXY_TLS: "false"
    image: opencloudeu/opencloud:latest
    logging:
      driver: local
    networks:
      opencloud-net: null
    ports:
      - mode: ingress
        target: 9200
        published: "9200"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /home/admin/opencloud-compose/config/opencloud/csp.yaml
        target: /etc/opencloud/csp.yaml
        bind:
          create_host_path: true
      - type: bind
        source: /home/admin/opencloud-compose/config/opencloud/banned-password-list.txt
        target: /etc/opencloud/banned-password-list.txt
        bind:
          create_host_path: true
      - type: bind
        source: /mnt/docker/opencloud/config
        target: /etc/opencloud
        bind:
          create_host_path: true
      - type: bind
        source: /mnt/docker/opencloud/data
        target: /var/lib/opencloud
        bind:
          create_host_path: true
networks:
  opencloud-net:
    name: opencloud-compose_opencloud-net
```

I can´t see how notifications may work or not
I am experimenting now with labels to make it easier to deploy
