### ISSUE TITLE
Feature request: Traefik with dns challenge options for certificates

### ISSUE THREAD

**Issue by DevonCasey** [opencloud-eu/opencloud-compose#40]
## Is your feature request related to a problem? Please describe.
For obtaining Let's Encrypt certificates that are validated against a domain a user owns, there is no existing option to enable traefik to support this. Users will need to implement their own unofficially supported configurations to obtain certificates this way. 

## Describe the solution you'd like
 Docker override files could be the most friendly solution, something like: 

traefik.cloudflare.yml
```
services:
  traefik:
    command:
      - "--certificatesResolvers.http.acme.email=${TRAEFIK_ACME_EMAIL:-example@example.com}"
      - "--certificatesResolvers.http.acme.caserver=${TRAEFIK_ACME_CASERVER:-https://acme-staging-v02.api.letsencrypt.org/directory}
      - "--certificatesResolvers.http.acme.dnschallenge.provider=cloudflare"
      - "--certificatesResolvers.http.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL} 
      - CF_API_TOKEN=${CF_API_TOKEN}
```

.env
```
## Cloudflare DNS Challenge for Traefik Settings ##
# The token used requires the following permissions:
# - Zone:DNS:Edit
CF_API_EMAIL= 
CF_DNS_API=
```

I only have an example for using cloudflare as its what I use.

## Describe alternatives you've considered
You can also use environment variables for each provider .env file and new commands in traefik's compose file to send to docker. This solution may get messy if multiple providers are supported, as they would need to be commented or uncommented in the compose file as needed. 

## Additional context
I am unsure if the emails should have defaults or not.
