### ISSUE TITLE
Nginx Error 502 while deploying via Portainer

### ISSUE THREAD

**Issue by mitexleo** [opencloud-eu/opencloud-compose#54]
Please add an Nginx configuration to the repo. I'm getting error 502 with the following config (used to work for OCIS):

```
server {

    server_name cloud.example.com;

    location / {
        proxy_pass http://localhost:9200;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
	client_max_body_size 0;
    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl http2; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/cloud.example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/cloud.example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = cloud.examle.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;

    server_name cloud.example.com;
    return 404; # managed by Certbot


}
```

Docker Compose:

```
name: opencloud-compose
services:
  collabora:
    cap_add:
      - MKNOD
    command:
      - coolconfig generate-proof-key && /start-collabora-online.sh
    entrypoint:
      - /bin/bash
      - -c
    environment:
      DONT_GEN_SSL_CERT: "YES"
      aliasgroup1: https://wopiserver.example.com:443
      extra_params: |
        --o:ssl.enable=false \
        --o:ssl.ssl_verification=true \
        --o:ssl.termination=true \
        --o:welcome.enable=false \
        --o:net.frame_ancestors=cloud.example.com
      password: redacted
      username: admin
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - "exec 3<>/dev/tcp/127.0.0.1/9980 && echo -e 'GET /hosting/discovery HTTP/1.1\r\nHost: localhost:9980\r\n\r\n' >&3 && head -n 1 <&3 | grep '200 OK'"
    image: collabora/code:25.04.1.1.1
    logging:
      driver: local
    networks:
      opencloud-net: null
    ports:
      - mode: ingress
        target: 9980
        published: "9980"
        protocol: tcp
    restart: always
  collaboration:
    command:
      - -c
      - opencloud collaboration server
    depends_on:
      collabora:
        condition: service_healthy
        required: true
      opencloud:
        condition: service_started
        required: true
    entrypoint:
      - /bin/sh
    environment:
      COLLABORATION_APP_ADDR: https://collabora.example.com
      COLLABORATION_APP_ICON: https://collabora.example.com/favicon.ico
      COLLABORATION_APP_INSECURE: "true"
      COLLABORATION_APP_NAME: CollaboraOnline
      COLLABORATION_APP_PRODUCT: Collabora
      COLLABORATION_CS3API_DATAGATEWAY_INSECURE: "true"
      COLLABORATION_GRPC_ADDR: 0.0.0.0:9301
      COLLABORATION_HTTP_ADDR: 0.0.0.0:9300
      COLLABORATION_LOG_LEVEL: info
      COLLABORATION_WOPI_SRC: https://wopiserver.example.com
      MICRO_REGISTRY: nats-js-kv
      MICRO_REGISTRY_ADDRESS: opencloud:9233
      OC_URL: https://cloud.example.com
    image: opencloudeu/opencloud-rolling:latest
    logging:
      driver: local
    networks:
      opencloud-net: null
    ports:
      - mode: ingress
        target: 9300
        published: "9305"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /mnt/opencloud/config
        target: /etc/opencloud
        bind:
          create_host_path: true
  opencloud:
    command:
      - -c
      - opencloud init || true; opencloud server
    entrypoint:
      - /bin/sh
    environment:
      COLLABORA_DOMAIN: collabora.example.com
      FRONTEND_APP_HANDLER_SECURE_VIEW_APP_ADDR: eu.opencloud.api.collaboration.CollaboraOnline
      FRONTEND_ARCHIVER_MAX_SIZE: "10000000000"
      GATEWAY_GRPC_ADDR: 0.0.0.0:9142
      GRAPH_AVAILABLE_ROLES: b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5,a8d5fe5e-96e3-418d-825b-534dbdf22b99,fb6c3e19-e378-47e5-b277-9732f9de6e21,58c63c02-1d89-4572-916a-870abc5a1b7d,2d00ce52-1fc2-4dbc-8b95-a73b73395f5a,1c996275-f1c9-4e71-abdf-a42f6495e960,312c0871-5ef7-4b3a-85b6-0e4074c64049,aa97fe03-7980-45ac-9e50-b325749fd7e6
      IDM_CREATE_DEMO_USERS: "false"
      NATS_NATS_HOST: 0.0.0.0
      NOTIFICATIONS_SMTP_AUTHENTICATION: ""
      NOTIFICATIONS_SMTP_ENCRYPTION: none
      NOTIFICATIONS_SMTP_HOST: ""
      NOTIFICATIONS_SMTP_INSECURE: ""
      NOTIFICATIONS_SMTP_PASSWORD: ""
      NOTIFICATIONS_SMTP_PORT: ""
      NOTIFICATIONS_SMTP_SENDER: OpenCloud notifications <notifications@cloud.example.com>
      NOTIFICATIONS_SMTP_USERNAME: ""
      OC_ADD_RUN_SERVICES: notifications
      OC_INSECURE: "false"
      OC_LOG_COLOR: "false"
      OC_LOG_LEVEL: info
      OC_LOG_PRETTY: "false"
      OC_PASSWORD_POLICY_BANNED_PASSWORDS_LIST: banned-password-list.txt
      OC_URL: https://cloud.example.com
      PROXY_CSP_CONFIG_FILE_LOCATION: /etc/opencloud/csp.yaml
      PROXY_ENABLE_BASIC_AUTH: "false"
      PROXY_HTTP_ADDR: 0.0.0.0:9200
      PROXY_TLS: "false"
    image: opencloudeu/opencloud-rolling:latest
    logging:
      driver: local
    networks:
      opencloud-net: null
    ports:
      - mode: ingress
        target: 9200
        published: "9200"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /root/opencloud-compose/config/opencloud/csp.yaml
        target: /etc/opencloud/csp.yaml
        bind:
          create_host_path: true
      - type: bind
        source: /root/opencloud-compose/config/opencloud/banned-password-list.txt
        target: /etc/opencloud/banned-password-list.txt
        bind:
          create_host_path: true
      - type: bind
        source: /mnt/opencloud/config
        target: /etc/opencloud
        bind:
          create_host_path: true
      - type: bind
        source: /mnt/opencloud/data
        target: /var/lib/opencloud
        bind:
          create_host_path: true
      - type: bind
        source: /mnt/opencloud/apps
        target: /var/lib/opencloud/web/assets/apps
        bind:
          create_host_path: true
networks:
  opencloud-net:
    name: opencloud-compose_opencloud-net
```

Log:
[_opencloud-opencloud-1_logs.txt](https://github.com/user-attachments/files/20953328/_opencloud-opencloud-1_logs.txt)

**Comment by micbar** [comment]
From my first look, the Config looks good. Can you check if the openCloud container is healthy and if you can curl it on http://localhost:9200

**Comment by mitexleo** [comment]
> From my first look, the Config looks good. Can you check if the openCloud container is healthy and if you can curl it on http://localhost:9200

Will do. I think it would be awesome if you could add a valid nginx configuration example in the repository.

**Comment by mitexleo** [comment]
> > From my first look, the Config looks good. Can you check if the openCloud container is healthy and if you can curl it on http://localhost:9200
> 
> Will do. I think it would be awesome if you could add a valid nginx configuration example in the repository. 

Okay. It worked! The problem was I've put the configuration files and data directory in mounted s3 volume. I'm yet to test whether s3 integration is working or not (s3 variables are not in the compose file even though they were present in the

**Comment by mitexleo** [comment]
Unfortunately, S3 Integration is not working. Files are being stored in the local disk which doesn't have enough space. I think it's because the compose file doesn't have the s3 configuration. 

![signal-2025-06-30-16-28-09-805~2.png](https://github.com/user-attachments/assets/4073502c-eb75-4c83-9e1d-034ba81d62fa)

@micbar Any guidance would be appreciated.


I added the region like that because of https://github.com/opencloud-eu/opencloud/discussions/1082#discussioncomment-13605059

**Comment by mitexleo** [comment]
> Unfortunately, S3 Integration is not working. Files are being stored in the local disk which doesn't have enough space. I think it's because the compose file doesn't have the s3 configuration. 
> 
> ![signal-2025-06-30-16-28-09-805~2.png](https://github.com/user-attachments/assets/4073502c-eb75-4c83-9e1d-034ba81d62fa)
> 
> @micbar Any guidance would be appreciated.
> 
> 
> I added the region like that because of https://github.com/opencloud-eu/opencloud/discussions/1082#discussioncomment-13605059

My bad. I forgot to add storage/decomposed.yml in .env ..

**Comment by mitexleo** [comment]
Everything except Collabora is working as expected.  

Here's the compose file: 

```
name: opencloud
services:
  collabora:
    cap_add:
      - MKNOD
    command:
      - coolconfig generate-proof-key && /start-collabora-online.sh
    entrypoint:
      - /bin/bash
      - -c
    environment:
      DONT_GEN_SSL_CERT: "YES"
      aliasgroup1: https://wopiserver.example.com:443
      extra_params: |
        --o:ssl.enable=false \
        --o:ssl.ssl_verification=true \
        --o:ssl.termination=true \
        --o:welcome.enable=false \
        --o:net.frame_ancestors=cloud.example.com
      password: redacted
      username: admin
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - "exec 3<>/dev/tcp/127.0.0.1/9980 && echo -e 'GET /hosting/discovery HTTP/1.1\r\nHost: localhost:9980\r\n\r\n' >&3 && head -n 1 <&3 | grep '200 OK'"
    image: collabora/code:25.04.1.1.1
    logging:
      driver: local
    networks:
      opencloud-net: null
    ports:
      - mode: ingress
        target: 9980
        published: "9980"
        protocol: tcp
    restart: always
  collaboration:
    command:
      - -c
      - opencloud collaboration server
    depends_on:
      collabora:
        condition: service_healthy
        required: true
      opencloud:
        condition: service_started
        required: true
    entrypoint:
      - /bin/sh
    environment:
      COLLABORATION_APP_ADDR: https://collabora.example.com
      COLLABORATION_APP_ICON: https://collabora.example.com/favicon.ico
      COLLABORATION_APP_INSECURE: "true"
      COLLABORATION_APP_NAME: CollaboraOnline
      COLLABORATION_APP_PRODUCT: Collabora
      COLLABORATION_CS3API_DATAGATEWAY_INSECURE: "true"
      COLLABORATION_GRPC_ADDR: 0.0.0.0:9301
      COLLABORATION_HTTP_ADDR: 0.0.0.0:9300
      COLLABORATION_LOG_LEVEL: info
      COLLABORATION_WOPI_SRC: https://wopiserver.example.com
      MICRO_REGISTRY: nats-js-kv
      MICRO_REGISTRY_ADDRESS: opencloud:9233
      OC_URL: https://cloud.example.com
    image: opencloudeu/opencloud-rolling:latest
    logging:
      driver: local
    networks:
      opencloud-net: null
    ports:
      - mode: ingress
        target: 9300
        published: "9300"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /root/oc/config
        target: /etc/opencloud
        bind:
          create_host_path: true
  opencloud:
    command:
      - -c
      - opencloud init || true; opencloud server
    entrypoint:
      - /bin/sh
    environment:
      COLLABORA_DOMAIN: collabora.example.com
      FRONTEND_APP_HANDLER_SECURE_VIEW_APP_ADDR: eu.opencloud.api.collaboration.CollaboraOnline
      FRONTEND_ARCHIVER_MAX_SIZE: "10000000000"
      GATEWAY_GRPC_ADDR: 0.0.0.0:9142
      GRAPH_AVAILABLE_ROLES: b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5,a8d5fe5e-96e3-418d-825b-534dbdf22b99,fb6c3e19-e378-47e5-b277-9732f9de6e21,58c63c02-1d89-4572-916a-870abc5a1b7d,2d00ce52-1fc2-4dbc-8b95-a73b73395f5a,1c996275-f1c9-4e71-abdf-a42f6495e960,312c0871-5ef7-4b3a-85b6-0e4074c64049,aa97fe03-7980-45ac-9e50-b325749fd7e6
      IDM_CREATE_DEMO_USERS: "false"
      NATS_NATS_HOST: 0.0.0.0
      NOTIFICATIONS_SMTP_AUTHENTICATION: ""
      NOTIFICATIONS_SMTP_ENCRYPTION: none
      NOTIFICATIONS_SMTP_HOST: ""
      NOTIFICATIONS_SMTP_INSECURE: ""
      NOTIFICATIONS_SMTP_PASSWORD: ""
      NOTIFICATIONS_SMTP_PORT: ""
      NOTIFICATIONS_SMTP_SENDER: OpenCloud notifications <notifications@cloud.example.com>
      NOTIFICATIONS_SMTP_USERNAME: ""
      OC_ADD_RUN_SERVICES: notifications
      OC_INSECURE: "false"
      OC_LOG_COLOR: "false"
      OC_LOG_LEVEL: info
      OC_LOG_PRETTY: "false"
      OC_PASSWORD_POLICY_BANNED_PASSWORDS_LIST: banned-password-list.txt
      OC_URL: https://cloud.example.com
      PROXY_CSP_CONFIG_FILE_LOCATION: /etc/opencloud/csp.yaml
      PROXY_ENABLE_BASIC_AUTH: "false"
      PROXY_HTTP_ADDR: 0.0.0.0:9200
      PROXY_TLS: "false"
      STORAGE_SYSTEM_DRIVER: decomposed
      STORAGE_USERS_DECOMPOSEDS3_ACCESS_KEY: 
      STORAGE_USERS_DECOMPOSEDS3_BUCKET: 
      STORAGE_USERS_DECOMPOSEDS3_ENDPOINT: https://s3.eu-central-003.backblazeb2.com
      STORAGE_USERS_DECOMPOSEDS3_REGION: eu-central #It needs to be exactly like this
      STORAGE_USERS_DECOMPOSEDS3_SECRET_KEY: 
      STORAGE_USERS_DRIVER: decomposeds3
      STORAGE_USERS_EVENTS_NUM_CONSUMERS: "5"
    image: opencloudeu/opencloud-rolling:latest
    logging:
      driver: local
    networks:
      opencloud-net: null
    ports:
      - mode: ingress
        target: 9200
        published: "9200"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /root/opencloud/config/opencloud/csp.yaml
        target: /etc/opencloud/csp.yaml
        bind:
          create_host_path: true
      - type: bind
        source: /root/opencloud/config/opencloud/banned-password-list.txt
        target: /etc/opencloud/banned-password-list.txt
        bind:
          create_host_path: true
      - type: bind
        source: /root/oc/config
        target: /etc/opencloud
        bind:
          create_host_path: true
      - type: bind
        source: /root/oc/data
        target: /var/lib/opencloud
        bind:
          create_host_path: true
      - type: bind
        source: /root/oc/apps
        target: /var/lib/opencloud/web/assets/apps
        bind:
          create_host_path: true
networks:
  opencloud-net:
    name: opencloud_opencloud-net
```

Nginx Config:

```
# HTTP server block to redirect to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name *.example.com;

    # Redirect all HTTP traffic to HTTPS
    return 301 https://$host$request_uri;
}

# HTTPS server block for cloud.example.com
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name cloud.example.com;

    # SSL configuration for Certbot (same for all services)
    ssl_certificate /etc/letsencrypt/live/cloud.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cloud.example.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Logging configuration
    access_log /var/log/nginx/example_access.log;
    error_log /var/log/nginx/example_error.log;
    client_max_body_size 0;
    # Reverse proxy to opencloud service
    location / {
        proxy_pass http://127.0.0.1:9200;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Updated HTTPS server block for collabora.example.com
server {
    listen 443 ssl http2;
    server_name collabora.example.com;

    # SSL configuration (same as opencloud)
    ssl_certificate /etc/letsencrypt/live/cloud.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cloud.example.com/privkey.pem;

    client_max_body_size 0;

    # Static files
    location ^~ /browser {
        proxy_pass http://127.0.0.1:9980;
        proxy_set_header Host $host;
    }

    # WOPI discovery URL
    location ^~ /hosting/discovery {
        proxy_pass http://127.0.0.1:9980;
        proxy_set_header Host $host;
    }

    # Capabilities
    location ^~ /hosting/capabilities {
        proxy_pass http://127.0.0.1:9980;
        proxy_set_header Host $host;
    }

    # Main websocket
    location ~ ^/cool/(.*)/ws$ {
        proxy_pass http://127.0.0.1:9980;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 36000s;
    }

    # Download, presentation, and image upload
    location ~ ^/(c|l)ool {
        proxy_pass http://127.0.0.1:9980;
        proxy_set_header Host $host;
    }

    # Admin Console websocket
    location ^~ /cool/adminws {
        proxy_pass http://127.0.0.1:9980;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 36000s;
    }
}

# HTTPS server block for wopiserver.example.com
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name wopiserver.examplet.com;

    # SSL configuration for Certbot (same for all services)
    ssl_certificate /etc/letsencrypt/live/cloud.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cloud.example.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Logging configuration
    access_log /var/log/nginx/opencloud_access.log;
    error_log /var/log/nginx/opencloud_error.log;

    client_max_body_size 0;

    # Reverse proxy to collaboration service
    location / {
        proxy_pass http://127.0.0.1:9300;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

```

This is the issue I have with Collabora (I have only 3GB left on the server):

![Image](https://github.com/user-attachments/assets/807279d8-088f-4e18-bb1e-a6bce08e46ad)
