### ISSUE TITLE
Run OpenCloud with existing Traefik, Tika and Collabora setup in seperate containers

### ISSUE THREAD

**Issue by Daniel-WW** [opencloud-eu/opencloud-compose#8]
Hi,

I would like to run OpenCloud in my existing Docker environment.  
I already have a working Traefik reverse proxy setup, as well as running containers for Apache Tika, Collabora Online and many other applications. 

I want to integrate OpenCloud as a separate container using its own `docker-compose.opencloud.yml` file.  
I don't want to install or run Traefik, Collabora, or Tika again – those services are already running.

---

#### My goal:

- Run OpenCloud with its own Docker Compose file 
- Connect it to my existing external Docker network (`traefik_proxy`)
- Use Traefik labels to expose it via HTTPS
- Let it connect to my running `tika` and `collabora` containers

---

#### Questions:

1. Is it possible to run OpenCloud this way, using only the main service and connecting to other containers?
2. Do I need to set specific environment variables like `COLLABORA_URL` or `TIKA_URL` to make this work?
3. Is there a minimal required set of containers I need from OpenCloud if some services already exist?

---

#### Example Compose:

```yaml
services:
  opencloud:
    image: opencloudui/opencloud:latest
    environment:
      - COLLABORA_URL=http://collabora:9980
      - TIKA_URL=http://tika:9998
      - ...
    labels:
      - traefik.enable=true
      - traefik.http.routers.opencloud.rule=Host(`cloud.example.com`)
      - ...
    networks:
      - traefik_proxy

...

```

Has anyone had experience with a similar setup? I hope I was able to explain my concerns as an "IT amateur" somewhat clearly.

Thanks in advance.
