### ISSUE TITLE
Add minimal docker compose example for using a standalone collabora docker container

### ISSUE THREAD

**Issue by SHU-red** [opencloud-eu/opencloud-compose#9]
Sorry im really struggling with all the env-vars and networking around docker with your inheriting docker-compose file

Pretty sure its just me not understanding things, but i tried to run

- opencloud in a separate compose/stack
- collabora in a spearate compose/stack
- only using ip-addresses and http

Is it possible to run collabora "standalone" similar to below:

```yaml
services:
  collabora:
    image: collabora/code:25.04.1.1.1
    container_name: collabora
    network_mode: bridge
    # release notes: https://www.collaboraonline.com/release-notes/
    environment:
      username: admin
      password: admin
    ports:
      - <colllabora_port>:<colllabora_port>
    cap_add:
      - MKNOD
    logging:
      driver: local
    restart: always
    entrypoint: ['/bin/bash', '-c']
    command: ['coolconfig generate-proof-key && /start-collabora-online.sh']
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/127.0.0.1/9980 && echo -e 'GET /hosting/discovery HTTP/1.1\r\nHost: localhost:9980\r\n\r\n' >&3 && head -n 1 <&3 | grep '200 OK'"]
```

And opencloud "standalone" like below:
```yaml

services:
  opencloud:
    image: opencloudeu/opencloud-rolling:latest
    container_name: opencloud
    network_mode: bridge
    environment:
      - OC_INSECURE=true
      - PROXY_HTTP_ADDR=0.0.0.0:9200
      - OC_URL=https://192.168.178.55:9200
    restart: always
    volumes:
      - oc_config:/etc/opencloud:Z
      - oc_data:/var/lib/opencloud:Z
    ports:
      - '9200:9200'
```

- What ports need to be open on collabora side
- What environment variables on opencloud side are necessary

to point opencloud via e.g. http://192.168.178.55:<colllabora_port>

Or am i thinking the wrong way? Im assuming that there may be more paths to utilize collabora running itsself by other services and not exclusively lock it down into openclouds stack/network thing

Feel free to correct me since i know that i only have a limited understanding of these things
